includes:
  - "$RUNNING_NG_PACKAGE_DATA/base/runbms.yml"

suites:
  dacapo-23.9-RC3-chopin-ci:
    type: DaCapo
    # Need running-ng to support 23.9
    release: evaluation
    path: "DACAPO_PATH/dacapo-23.9-RC3-chopin.jar"
    minheap: mmtk-openjdk-11-MarkCompact
    # Min heap values are from dacapo-evaluation-git-04132797
    minheap_values:
      mmtk-openjdk-11-MarkCompact:
        avrora: 8
        batik: 426
        biojava: 197
        cassandra: 117
        eclipse: 439
        fop: 24
        graphchi: 195
        h2: 1122
        h2o: 136
        jme: 236
        jython: 48
        kafka: 243
        luindex: 25
        lusearch: 36
        pmd: 291
        spring: 110
        sunflow: 37
        tradebeans: .inf
        tradesoap: .inf
        tomcat: 55
        xalan: 19
        zxing: 427
      nominal-heap-sizes:
        avrora: 7
        batik: 192
        biojava: 97
        cassandra: 74
        eclipse: 346
        fop: 17
        graphchi: 179
        h2: 506
        h2o: 102
        jme: 29
        jython: 29
        kafka: 207
        luindex: 44
        lusearch: 19
        pmd: 114
        spring: 47
        sunflow: 25
        tradebeans: 101
        tradesoap: 89
        tomcat: 17
        xalan: 9
        zxing: 66
    timing_iteration: 1
    timeout: 7200

overrides:
  invocations: 1
  remote_host: null

modifiers:
  mmtk_gc:
    type: "EnvVar"
    var: "MMTK_PLAN"
    val: "{0}"
  fail_on_oom:
    type: JVMArg
    val: "-XX:+CrashOnOutOfMemoryError"
  preserve:
    type: ProgramArg
    val: "-preserve"

plugins:
  keep_stdout_stderr:
    type: CopyFile
    patterns:
      - "scratch/stdout.log"
      - "scratch/stderr.log"

runtimes:
  jdk11-master:
    type: OpenJDK
    release: 11
    home: "/home/runner/work/mmtk-openjdk/mmtk-openjdk/bundles/jdk"

configs:
  - "jdk11-master|ms|s|fail_on_oom|tph|preserve|mmtk_gc-SemiSpace"
  - "jdk11-master|ms|s|fail_on_oom|tph|preserve|mmtk_gc-GenCopy"
  - "jdk11-master|ms|s|fail_on_oom|tph|preserve|mmtk_gc-Immix"
  - "jdk11-master|ms|s|fail_on_oom|tph|preserve|mmtk_gc-GenImmix"
  - "jdk11-master|ms|s|fail_on_oom|tph|preserve|mmtk_gc-StickyImmix"
  - "jdk11-master|ms|s|fail_on_oom|tph|preserve|mmtk_gc-MarkSweep"
  - "jdk11-master|ms|s|fail_on_oom|tph|preserve|mmtk_gc-MarkCompact"

benchmarks:
  dacapo-23.9-RC3-chopin-ci:
