includes:
  - "./base.yml"

configs:
  - "jdk11-master|ms|s|fail_on_oom|tph|preserve|mmtk_gc-SemiSpace"
  - "jdk11-master|ms|s|fail_on_oom|tph|preserve|mmtk_gc-GenCopy"
  - "jdk11-master|ms|s|fail_on_oom|tph|preserve|mmtk_gc-Immix"
  - "jdk11-master|ms|s|fail_on_oom|tph|preserve|mmtk_gc-GenImmix"
  - "jdk11-master|ms|s|fail_on_oom|tph|preserve|mmtk_gc-StickyImmix"
  - "jdk11-master|ms|s|fail_on_oom|tph|preserve|mmtk_gc-MarkSweep"
  - "jdk11-master|ms|s|fail_on_oom|tph|preserve|mmtk_gc-MarkCompact"
  # TODO: We need to disable compressed oops for Compressor temporarily until it supports
  # discontiguous spaces.
  - "jdk11-master|ms|s|fail_on_oom|tph|preserve|no_compressed_oops|mmtk_gc-Compressor"

# This will be expanded in CI when we run with the config. Keep a new line at the end.
benchmarks:
  dacapo-23.9-RC3-chopin-ci:
