results:
  linux-x64:
    fastdebug:
      avrora:
        SemiSpace:
          pass: true
        GenCopy:
          pass: true
        Immix:
          pass: true
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: true
        MarkCompact:
          pass: true
      batik:
        SemiSpace:
          pass: true
        GenCopy:
          pass: true
        Immix:
          pass: true
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: true
        MarkCompact:
          pass: true
      biojava:
        SemiSpace:
          pass: false
        GenCopy:
          pass: true
        Immix:
          pass: false
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: false
        MarkCompact:
          pass: false
      cassandra:
        SemiSpace:
          pass: true
        GenCopy:
          pass: true
        Immix:
          pass: false
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
          note: non-deterministic
        MarkSweep:
          pass: false
        MarkCompact:
          pass: false
      eclipse:
        SemiSpace:
          pass: true
        GenCopy:
          pass: true
        Immix:
          pass: true
        GenImmix:
          pass: true
        StickyImmix:
          pass: false
        MarkSweep:
          pass: false
        MarkCompact:
          pass: false
      fop:
        SemiSpace:
          pass: true
        GenCopy:
          pass: true
          note: non-deterministic
        Immix:
          pass: true
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: false
        MarkCompact:
          pass: true
      graphchi:
        SemiSpace:
          pass: true
        GenCopy:
          pass: true
        Immix:
          pass: true
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: false
        MarkCompact:
          pass: false
      h2:
        SemiSpace:
          pass: false
        GenCopy:
          pass: true
        Immix:
          pass: false
        GenImmix:
          pass: true
        StickyImmix:
          pass: false
        MarkSweep:
          pass: false
        MarkCompact:
          pass: false
      h2o:
        SemiSpace:
          pass: true
        GenCopy:
          pass: true
        Immix:
          pass: true
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: false
        MarkCompact:
          pass: false
      jme:
        SemiSpace:
          pass: true
        GenCopy:
          pass: true
        Immix:
          pass: true
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: true
        MarkCompact:
          pass: true
      jython:
        SemiSpace:
          pass: true
        GenCopy:
          pass: false
        Immix:
          pass: true
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: false
        MarkCompact:
          pass: false
      kafka:
        SemiSpace:
          pass: true
        GenCopy:
          pass: true
        Immix:
          pass: true
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: true
        MarkCompact:
          pass: false
      luindex:
        SemiSpace:
          pass: true
        GenCopy:
          pass: true
        Immix:
          pass: true
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: true
        MarkCompact:
          pass: false
      lusearch:
        SemiSpace:
          pass: true
        GenCopy:
          pass: true
        Immix:
          pass: false
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: false
        MarkCompact:
          pass: false
      pmd:
        SemiSpace:
          pass: true
        GenCopy:
          pass: false
        Immix:
          pass: true
        GenImmix:
          pass: false
        StickyImmix:
          pass: false
        MarkSweep:
          pass: false
        MarkCompact:
          pass: false
      sunflow:
        SemiSpace:
          pass: true
        GenCopy:
          pass: true
        Immix:
          pass: true
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: false
        MarkCompact:
          pass: false
      tomcat:
        SemiSpace:
          pass: true
        GenCopy:
          pass: true
        Immix:
          pass: false
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: false
        MarkCompact:
          pass: false
      xalan:
        SemiSpace:
          pass: true
        GenCopy:
          pass: true
        Immix:
          pass: true
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: true
        MarkCompact:
          pass: false
      zxing:
        SemiSpace:
          pass: true
        GenCopy:
          pass: true
        Immix:
          pass: true
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: true
        MarkCompact:
          pass: true

    release:
      avrora:
        SemiSpace:
          pass: true
        GenCopy:
          pass: true
        Immix:
          pass: true
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: true
        MarkCompact:
          pass: true
      batik:
        SemiSpace:
          pass: true
        GenCopy:
          pass: true
        Immix:
          pass: true
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: true
        MarkCompact:
          pass: true
      biojava:
        SemiSpace:
          pass: true
        GenCopy:
          pass: true
        Immix:
          pass: true
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: true
        MarkCompact:
          pass: true
      cassandra:
        SemiSpace:
          pass: true
        GenCopy:
          pass: true
        Immix:
          pass: true
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: false
        MarkCompact:
          pass: true
      eclipse:
        SemiSpace:
          pass: true
        GenCopy:
          pass: true
        Immix:
          pass: true
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: false
        MarkCompact:
          pass: true
      fop:
        SemiSpace:
          pass: true
        GenCopy:
          pass: true
        Immix:
          pass: true
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: false
        MarkCompact:
          pass: true
      graphchi:
        SemiSpace:
          pass: true
        GenCopy:
          pass: true
        Immix:
          pass: true
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: true
        MarkCompact:
          pass: true
      h2:
        SemiSpace:
          pass: true
        GenCopy:
          pass: true
        Immix:
          pass: true
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: true
        MarkCompact:
          pass: true
      h2o:
        SemiSpace:
          pass: true
        GenCopy:
          pass: true
        Immix:
          pass: true
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: true
        MarkCompact:
          pass: true
      jme:
        SemiSpace:
          pass: true
        GenCopy:
          pass: true
        Immix:
          pass: true
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: true
        MarkCompact:
          pass: true
      jython:
        SemiSpace:
          pass: true
        GenCopy:
          pass: false
        Immix:
          pass: true
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: false
        MarkCompact:
          pass: true
      kafka:
        SemiSpace:
          pass: true
        GenCopy:
          pass: true
        Immix:
          pass: true
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: true
        MarkCompact:
          pass: true
      luindex:
        SemiSpace:
          pass: true
        GenCopy:
          pass: true
        Immix:
          pass: true
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: true
        MarkCompact:
          pass: true
      lusearch:
        SemiSpace:
          pass: true
        GenCopy:
          pass: true
        Immix:
          pass: true
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: true
        MarkCompact:
          pass: true
      pmd:
        SemiSpace:
          pass: true
        GenCopy:
          pass: false
        Immix:
          pass: true
        GenImmix:
          pass: false
        StickyImmix:
          pass: false
        MarkSweep:
          pass: true
        MarkCompact:
          pass: true
      sunflow:
        SemiSpace:
          pass: true
        GenCopy:
          pass: true
        Immix:
          pass: true
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: true
        MarkCompact:
          pass: true
      tomcat:
        SemiSpace:
          pass: true
        GenCopy:
          pass: true
        Immix:
          pass: true
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: true
        MarkCompact:
          pass: true
      xalan:
        SemiSpace:
          pass: true
        GenCopy:
          pass: false
        Immix:
          pass: true
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: true
        MarkCompact:
          pass: true
      zxing:
        SemiSpace:
          pass: true
        GenCopy:
          pass: true
        Immix:
          pass: true
        GenImmix:
          pass: true
        StickyImmix:
          pass: true
        MarkSweep:
          pass: true
        MarkCompact:
          pass: true
