results:
  linux-x64:
    fastdebug:
      avrora:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
        Compressor: pass
      batik:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
        Compressor: pass
      biojava:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
        Compressor: pass
      cassandra:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: ignore
        MarkCompact: ignore
        Compressor: ignore
      eclipse:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: ignore
        MarkCompact: pass
        Compressor: pass
      fop:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: ignore
        MarkCompact: pass
        Compressor: pass
      graphchi:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
        Compressor: pass
      h2:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: ignore
        MarkCompact: pass
        Compressor: pass
      h2o:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
        Compressor: pass
      jme:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
        Compressor: pass
      jython:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: ignore
        MarkCompact: pass
        Compressor: pass
      kafka:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: ignore
        Compressor: pass
      luindex:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
        Compressor: pass
      lusearch:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: ignore
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
        Compressor: pass
      pmd:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
        Compressor: pass
      sunflow:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
        Compressor: pass
      tomcat:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
        Compressor: pass
      xalan:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: ignore
        MarkSweep: pass
        MarkCompact: pass
        Compressor: pass
      zxing:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
        Compressor: pass

    release:
      avrora:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
        Compressor: pass
      batik:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
        Compressor: pass
      biojava:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
        Compressor: pass
      cassandra:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: ignore
        MarkCompact: pass
        Compressor: pass
      eclipse:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: ignore
        MarkCompact: pass
        Compressor: pass
      fop:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: ignore
        MarkCompact: pass
        Compressor: pass
      graphchi:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
        Compressor: pass
      h2:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: ignore
        MarkCompact: pass
        Compressor: pass
      h2o:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: ignore
        MarkCompact: pass
        Compressor: pass
      jme:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
        Compressor: pass
      jython:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: ignore
        MarkCompact: pass
        Compressor: pass
      kafka:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
        Compressor: pass
      luindex:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
        Compressor: pass
      lusearch:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
        Compressor: pass
      pmd:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
        Compressor: pass
      sunflow:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
        Compressor: pass
      tomcat:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: ignore
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
        Compressor: pass
      xalan:
        SemiSpace: ignore
        GenCopy: ignore
        Immix: pass
        GenImmix: ignore
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
        Compressor: pass
      zxing:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
        Compressor: pass
