results:
  linux-x64:
    fastdebug:
      avrora:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
      batik:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
      biojava:
        SemiSpace: fail
        GenCopy: pass
        Immix: fail
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: fail
        MarkCompact: fail
      cassandra:
        SemiSpace: pass
        GenCopy: pass
        Immix: fail
        GenImmix: pass
        StickyImmix: ignore
        MarkSweep: fail
        MarkCompact: fail
      eclipse:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: fail
        MarkSweep: fail
        MarkCompact: fail
      fop:
        SemiSpace: pass
        GenCopy: ignore
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: fail
        MarkCompact: pass
      graphchi:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: fail
        MarkCompact: fail
      h2:
        SemiSpace: fail
        GenCopy: pass
        Immix: fail
        GenImmix: pass
        StickyImmix: fail
        MarkSweep: fail
        MarkCompact: fail
      h2o:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: fail
        MarkCompact: fail
      jme:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
      jython:
        SemiSpace: pass
        GenCopy: fail
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: fail
        MarkCompact: fail
      kafka:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: fail
      luindex:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: fail
      lusearch:
        SemiSpace: pass
        GenCopy: pass
        Immix: fail
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: fail
        MarkCompact: fail
      pmd:
        SemiSpace: pass
        GenCopy: fail
        Immix: pass
        GenImmix: fail
        StickyImmix: fail
        MarkSweep: fail
        MarkCompact: fail
      sunflow:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: fail
        MarkCompact: fail
      tomcat:
        SemiSpace: pass
        GenCopy: pass
        Immix: fail
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: fail
        MarkCompact: fail
      xalan:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: fail
      zxing:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass

    release:
      avrora:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
      batik:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
      biojava:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
      cassandra:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: fail
        MarkCompact: pass
      eclipse:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: fail
        MarkCompact: pass
      fop:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: fail
        MarkCompact: pass
      graphchi:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
      h2:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
      h2o:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
      jme:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
      jython:
        SemiSpace: pass
        GenCopy: fail
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: fail
        MarkCompact: pass
      kafka:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
      luindex:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
      lusearch:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
      pmd:
        SemiSpace: pass
        GenCopy: fail
        Immix: pass
        GenImmix: fail
        StickyImmix: fail
        MarkSweep: pass
        MarkCompact: pass
      sunflow:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
      tomcat:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
      xalan:
        SemiSpace: pass
        GenCopy: fail
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
      zxing:
        SemiSpace: pass
        GenCopy: pass
        Immix: pass
        GenImmix: pass
        StickyImmix: pass
        MarkSweep: pass
        MarkCompact: pass
