#ifndef SHARE_GC_MMTK_THIRDPARTYHEAPBARRIERSET_HPP
#define SHARE_GC_MMTK_THIRDPARTYHEAPBARRIERSET_HPP

#include "mmtkBarrierSet.hpp"

typedef MMTkBarrierSet ThirdPartyHeapBarrierSet;

#endif // SHARE_GC_MMTK_THIRDPARTYHEAPBARRIERSET_HPP
