#ifndef MMTK_OPENJDK_MMTK_NO_BARRIER_SET_ASSEMBLER_X86_HPP
#define MMTK_OPENJDK_MMTK_NO_BARRIER_SET_ASSEMBLER_X86_HPP

#include "mmtkBarrierSetAssembler_x86.hpp"

class MMTkNoBarrierSetAssembler: public MMTkBarrierSetAssembler {};
#endif // MMTK_OPENJDK_MMTK_NO_BARRIER_SET_ASSEMBLER_X86_HPP
