#ifndef MMTK_OPENJDK_THIRD_PARTY_HEAP_BARRIER_SET_HPP
#define MMTK_OPENJDK_THIRD_PARTY_HEAP_BARRIER_SET_HPP

#include "mmtkBarrierSet.hpp"

typedef MMTkBarrierSet ThirdPartyHeapBarrierSet;

#endif // MMTK_OPENJDK_THIRD_PARTY_HEAP_BARRIER_SET_HPP
