name: Build OpenJDK Binding

on:
  workflow_call:

jobs:
  build-linux-x64:
    name: linux-x64
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        debug-level: ["fastdebug", "release"]
    steps:
    - name: Checkout MMTk OpenJDK binding
      uses: actions/checkout@v3
      with:
        path: ./git/mmtk-openjdk
    - name: Extract OpenJDK revision
      id: extract-openjdk-revision
      run: |
        OPENJDK_VERSION=`sed -n 's/^openjdk_version.=."\(.*\)"$/\1/p' < git/mmtk-openjdk/mmtk/Cargo.toml`
        echo "openjdk-revision=$OPENJDK_VERSION" >> $GITHUB_OUTPUT
    - name: Checkout OpenJDK
      uses: actions/checkout@v3
      with:
        repository: mmtk/openjdk
        path: ./git/openjdk
        ref: ${{ steps.extract-openjdk-revision.outputs.openjdk-revision }}
    - name: Setup environment
      run: ./.github/scripts/ci-setup.sh
      working-directory: ./git/mmtk-openjdk
    - name: Build MMTk OpenJDK ${{ matrix.debug-level }}
      run: |
        OPENJDK_PATH=$GITHUB_WORKSPACE/git/openjdk DEBUG_LEVEL=${{ matrix.debug-level }} OPENJDK_BUILD_TARGET=product-bundles ./.github/scripts/ci-build.sh
      working-directory: ./git/mmtk-openjdk
    - name: Upload bundles
      uses: actions/upload-artifact@v3
      with:
        name: linux-x86_64-server-${{ matrix.debug-level }}-bundles
        path: ./git/openjdk/build/linux-x86_64-normal-server-${{ matrix.debug-level }}/bundles/*_bin.tar.gz
        retention-days: 2
