name: Build OpenJDK Binding

on:
  workflow_call:
    inputs:
      debug-level:
        required: true
        type: string
      build-env-var:
        required: false
        type: string
      mmtk-core-repo:
        required: false
        type: string
      mmtk-core-ref:
        required: false
        type: string

jobs:
  build-linux-x64:
    name: linux-x64
    runs-on: ubuntu-22.04
    env:
      # This overrides OPENJDK_PATH in ci-common.sh
      # Note: We cannot use default environment variables (GITHUB_*) in the "env" context.  Use github.* instead.
      # See: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#default-environment-variables
      OPENJDK_PATH: ${{ github.workspace }}/git/openjdk
    steps:
    - name: Checkout MMTk OpenJDK binding
      uses: actions/checkout@v4
      with:
        path: ./git/mmtk-openjdk
    - name: Checkout OpenJDK
      run: ./git/mmtk-openjdk/.github/scripts/ci-checkout.sh
    - name: Patch mmtk-core version if needed
      if: ${{ inputs.mmtk-core-repo != '' || inputs.mmtk-core-ref != '' }}
      run: |
        pip3 install tomlkit
        python3 .github/scripts/patch-mmtk-dep.py mmtk/Cargo.toml ${{ inputs.mmtk-core-ref }} ${{ inputs.mmtk-core-repo }}
        cat mmtk/Cargo.toml
      working-directory: ./git/mmtk-openjdk
    - name: Setup environment
      run: ./.github/scripts/ci-setup.sh
      working-directory: ./git/mmtk-openjdk
    - name: Export build environemnt variables
      if: ${{ inputs.build-env-var != '' }}
      run: |
        echo "${{ inputs.build-env-var }}" >> $GITHUB_ENV
    - name: Export build suffix
      run: |
        if [ -z "${{ inputs.build-env-var }}" ]; then
          echo "BUILD_SUFFIX=normal" >> $GITHUB_ENV
        else
          escaped_build=$(echo "${{ inputs.build-env-var }}" | sed 's/ /_/g')
          echo "BUILD_SUFFIX=$escaped_build" >> $GITHUB_ENV
        fi
    - name: Build MMTk OpenJDK ${{ inputs.debug-level }}
      env:
        DEBUG_LEVEL: ${{ inputs.debug-level }}
        OPENJDK_BUILD_TARGET: product-bundles
      run: ./.github/scripts/ci-build.sh
      working-directory: ./git/mmtk-openjdk
    - name: Upload bundles
      uses: actions/upload-artifact@v4
      with:
        name: linux-x86_64-server-${{ inputs.debug-level }}-bundles-${{ env.BUILD_SUFFIX }}
        path: |
          ./git/openjdk/build/linux-x86_64-server-${{ inputs.debug-level }}/bundles/*_bin.tar.gz
          ./git/openjdk/build/linux-x86_64-server-${{ inputs.debug-level }}/bundles/*_bin-debug.tar.gz
        retention-days: 2
