name: "Test with DaCapo Chopin"

on:
  workflow_call:

jobs:
  normal-heap:
    uses: ./.github/workflows/run-dacapo-chopin-inner.yml
    with:
      config-file: "normal-heap.yml"
      heap-factor: "2.5"

  large-heap:
    uses: ./.github/workflows/run-dacapo-chopin-inner.yml
    with:
      config-file: "large-heap.yml"
      heap-factor: "7"
