# Extended tests for MMTk core. These tests are only executed on demand.

# TODO:
# - This is currently a duplicate of test-core-extended.yml. But we should only keep a subset of the essential tests in this workflow.
# - We should use dacapo chopin for testing.

name: Minimal tests for MMTk core

on:
  workflow_dispatch:
    inputs:
      mmtk-core-repo:
        required: false
        type: string
      mmtk-core-ref:
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # Normal build
  build-normal-fastdebug:
    uses: ./.github/workflows/build.yml
    with:
      debug-level: fastdebug
      mmtk-core-repo: ${{ inputs.mmtk-core-repo }}
      mmtk-core-ref: ${{ inputs.mmtk-core-ref }}

  # Feature build: only build fastdebug
  build-vo-bit:
    uses: ./.github/workflows/build.yml
    with:
      build-env-var: MMTK_VO_BIT=1
      debug-level: fastdebug
      mmtk-core-repo: ${{ inputs.mmtk-core-repo }}
      mmtk-core-ref: ${{ inputs.mmtk-core-ref }}

  build-extreme-assertions:
    uses: ./.github/workflows/build.yml
    with:
      build-env-var: MMTK_EXTREME_ASSERTIONS=1
      debug-level: fastdebug
      mmtk-core-repo: ${{ inputs.mmtk-core-repo }}
      mmtk-core-ref: ${{ inputs.mmtk-core-ref }}

  build-malloc-mark-sweep:
    uses: ./.github/workflows/build.yml
    with:
      # Test malloc mark sweep with extreme assertions
      build-env-var: MMTK_MALLOC_MARK_SWEEP=1 MMTK_EXTREME_ASSERTIONS=1
      debug-level: fastdebug
      mmtk-core-repo: ${{ inputs.mmtk-core-repo }}
      mmtk-core-ref: ${{ inputs.mmtk-core-ref }}

  build-mark-in-header:
    uses: ./.github/workflows/build.yml
    with:
      # Before we get other plans work with mark in header, we only test with malloc mark sweep.
      build-env-var: MMTK_MALLOC_MARK_SWEEP=1 MMTK_MARK_IN_HEADER=1
      debug-level: fastdebug
      mmtk-core-repo: ${{ inputs.mmtk-core-repo }}
      mmtk-core-ref: ${{ inputs.mmtk-core-ref }}

  run-dacapo-2006:
    needs:
      - build-normal-fastdebug
      - build-vo-bit
      - build-extreme-assertions
      - build-malloc-mark-sweep
      - build-mark-in-header
    uses: ./.github/workflows/run-dacapo-2006.yml
